# Generated by Django 4.2 on 2023-04-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSM_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_post',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
