# Generated by Django 4.2 on 2023-04-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JSM_app', '0004_recomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomment',
            old_name='comment',
            new_name='content',
        ),
    ]
