# Generated by Django 4.2 on 2023-04-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JSM_app', '0005_rename_comment_recomment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomment',
            old_name='content',
            new_name='comment',
        ),
    ]
