# Generated by Django 4.1.7 on 2023-04-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_article_created_date_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_date',
        ),
    ]
